# Generated by Django 5.1 on 2024-09-10 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('horas_demandadas', models.IntegerField()),
                ('rol_requerido', models.CharField(max_length=100)),
                ('semana_inicio', models.IntegerField()),
                ('duracion_semanas', models.IntegerField()),
            ],
            options={
                'db_table': 'Proyecto',
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=100)),
                ('prioridad', models.IntegerField()),
                ('horas_promedio', models.IntegerField(default=40)),
            ],
            options={
                'db_table': 'Recurso',
            },
        ),
        migrations.CreateModel(
            name='TipoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('prioridad', models.IntegerField()),
            ],
            options={
                'db_table': 'TipoProyecto',
            },
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.IntegerField()),
                ('horas_disponibles', models.IntegerField(default=40)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recurso')),
            ],
            options={
                'db_table': 'Disponibilidad',
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.IntegerField()),
                ('horas_asignadas', models.IntegerField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proyecto')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recurso')),
            ],
            options={
                'db_table': 'Asignacion',
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tipo_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoproyecto'),
        ),
    ]
