# Generated by Django 5.1 on 2024-08-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proyectos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Proyecto')),
                ('proyecto', models.CharField(max_length=12, verbose_name='Proyecto')),
                ('lineaNegocio', models.CharField(max_length=6, verbose_name='Línea de Negocio')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de Proyecto')),
                ('cliente', models.IntegerField(blank=True, null=True, verbose_name='ID Cliente')),
                ('createDate', models.DateTimeField(verbose_name='Fecha de creación')),
                ('cierre', models.DateField(verbose_name='Cierre del proyecto')),
                ('egresosNoHHCLP', models.IntegerField(verbose_name='Egresos no HH CLP')),
                ('montoOfertaCLP', models.IntegerField(verbose_name='Monto Oferta CLP')),
                ('usoAgencia', models.BooleanField(default=0, verbose_name='Apoyo de Agencia')),
                ('ocupacionInicio', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Porcentaje de uso inicial')),
                ('disponibilidad', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Porcentaje de disponibilidad')),
                ('utilizacion', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Porcentaje de utilización')),
            ],
            options={
                'db_table': 'PROYECTOS',
            },
        ),
    ]
