# Generated by Django 5.1 on 2024-09-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ultimo_ejecucion', models.DateTimeField(auto_now=True)),
                ('ejecuciones_exitosas', models.IntegerField(default=0)),
                ('ejecuciones_fallidas', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Control de Asignación',
                'verbose_name_plural': 'Controles de Asignación',
                'db_table': 'AsignacionControl',
            },
        ),
    ]
