# Generated by Django 5.0.7 on 2024-08-01 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hh_estimado_detalle_semanal',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 31, 20, 49, 40, 55701), verbose_name='Fecha'),
        ),
    ]
