# Generated by Django 5.1 on 2024-08-26 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Empleado')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del empleado')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo o Rol del empleado')),
                ('telefono', models.CharField(max_length=15, verbose_name='Numero de contacto')),
                ('categoria', models.IntegerField()),
                ('horas_laborales', models.IntegerField(default=8, verbose_name='Jornada laboral')),
                ('disponibilidad', models.IntegerField(verbose_name='Horas disponible del empleado')),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupado', 'Ocupado')], max_length=20)),
            ],
            options={
                'db_table': 'EMPLEADOS',
            },
        ),
        migrations.CreateModel(
            name='asignacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Asignación')),
                ('horas_asignadas', models.IntegerField(verbose_name='Horas Asignadas')),
                ('categoria', models.IntegerField(verbose_name='Categoría del Empleado')),
                ('estado_empleado', models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupado', 'Ocupado')], max_length=20, verbose_name='Estado del Empleado')),
                ('disponibilidad_restante', models.IntegerField(verbose_name='Disponibilidad Restante del Empleado')),
                ('ocupacion', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ocupación')),
                ('disponibilidad', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Disponibilidad')),
                ('utilizacion', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Utilización')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proyectos', verbose_name='Proyecto Asignado')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleado', verbose_name='Empleado Asignado')),
            ],
            options={
                'db_table': 'ASIGNACION',
            },
        ),
    ]
