# Generated by Django 5.1 on 2024-08-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empleado_asignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='dias_proyecto',
            field=models.IntegerField(default=0, verbose_name='Cantidad de Días del Proyecto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignacion',
            name='total_horas_trabajadas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Total Horas Trabajadas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='disponibilidad_restante',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Disponibilidad Restante del Empleado'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='horas_asignadas',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Horas Asignadas'),
        ),
    ]
