# Generated by Django 5.1 on 2024-09-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_asignacioncontrol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacioncontrol',
            options={},
        ),
        migrations.RemoveField(
            model_name='asignacioncontrol',
            name='ejecuciones_exitosas',
        ),
        migrations.RemoveField(
            model_name='asignacioncontrol',
            name='ejecuciones_fallidas',
        ),
        migrations.AlterField(
            model_name='asignacioncontrol',
            name='fecha_ultimo_ejecucion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='asignacioncontrol',
            table=None,
        ),
    ]
