# Generated by Django 5.1 on 2024-09-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_asignacioncontrol_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacioncontrol',
            name='ejecuciones_exitosas',
            field=models.IntegerField(default=0),
        ),
    ]
