# Generated by Django 5.1 on 2024-08-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_asignacion_dias_proyecto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='dias_proyecto',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='total_horas_trabajadas',
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='disponibilidad_restante',
            field=models.IntegerField(verbose_name='Disponibilidad Restante del Empleado'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='horas_asignadas',
            field=models.IntegerField(verbose_name='Horas Asignadas'),
        ),
    ]
