# Generated by Django 5.1 on 2024-09-04 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_asignacion_dias_proyecto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('horas_demandadas', models.IntegerField()),
                ('rol_requerido', models.CharField(max_length=100)),
                ('semana', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=100)),
                ('prioridad', models.IntegerField()),
                ('horas_promedio', models.IntegerField(default=8)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('prioridad', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='disponibilidad',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='disponibilidad_restante',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='estado_empleado',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='ocupacion',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='utilizacion',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='semana',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='horas_asignadas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='asignacion',
            table=None,
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proyecto'),
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.IntegerField()),
                ('horas_disponibles', models.IntegerField(default=40)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recurso')),
            ],
        ),
        migrations.AddField(
            model_name='asignacion',
            name='recurso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.recurso'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tipo_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoproyecto'),
        ),
        migrations.DeleteModel(
            name='empleado',
        ),
        migrations.DeleteModel(
            name='proyectos',
        ),
    ]
