# Generated by Django 4.1.8 on 2024-08-08 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_hh_estimado_detalle_semanal_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='proyectosAAgrupar',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Proyecto')),
                ('proyecto', models.CharField(max_length=12, verbose_name='Proyecto')),
                ('lineaNegocio', models.CharField(max_length=6, verbose_name='Línea de Negocio')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de Proyecto')),
                ('cliente', models.IntegerField(blank=True, null=True, verbose_name='ID Cliente')),
                ('pm', models.CharField(max_length=60, verbose_name='Correo JP')),
                ('createDate', models.DateTimeField(verbose_name='Fecha de creación')),
                ('cierre', models.DateField(verbose_name='Cierre del proyecto')),
                ('primeraTarea', models.DateField(verbose_name='Primera Tarea Realizada')),
                ('ultimaTarea', models.DateField(verbose_name='Última tarea realizada')),
                ('egresosNoHHCLP', models.IntegerField(verbose_name='Egresos no HH CLP')),
                ('montoOfertaCLP', models.IntegerField(verbose_name='Monto Oferta CLP')),
                ('usoAgencia', models.BooleanField(default=0, verbose_name='Apoyo de Agencia')),
                ('desfaseDias', models.IntegerField(default=0, verbose_name='Desfase de días para el inicio del proyecto')),
                ('ocupacionInicio', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Porcentaje de uso inicial')),
            ],
        ),
        migrations.AlterField(
            model_name='hh_estimado_detalle_semanal',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 8, 15, 5, 38, 254733), verbose_name='Fecha'),
        ),
    ]
