# Generated by Django 4.1.8 on 2024-08-09 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_hh_estimado_detalle_semanal_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hh_estimado_detalle_semanal',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 14, 8, 6, 431815), verbose_name='Fecha'),
        ),
        migrations.AlterModelTable(
            name='historialcambios',
            table='HISTORIAL_CAMBIOS',
        ),
        migrations.AlterModelTable(
            name='perfilusuario',
            table='PERFIL_USUARIO',
        ),
        migrations.AlterModelTable(
            name='proyectosaagrupar',
            table='PROYECTOS_A_AGRUPAR',
        ),
    ]
