# Generated by Django 4.1.8 on 2024-08-21 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_perfilusuario_dvrun_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hh_estimado_detalle_semanal',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 17, 44, 44, 737450), verbose_name='Fecha'),
        ),
        migrations.AlterModelTable(
            name='perfilusuario',
            table='PERFIL_USUARIO',
        ),
    ]
