# Generated by Django 4.1.8 on 2024-08-23 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_hh_estimado_detalle_semanal_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectosaagrupar',
            name='desfaseDias',
        ),
        migrations.RemoveField(
            model_name='proyectosaagrupar',
            name='pm',
        ),
        migrations.RemoveField(
            model_name='proyectosaagrupar',
            name='primeraTarea',
        ),
        migrations.RemoveField(
            model_name='proyectosaagrupar',
            name='ultimaTarea',
        ),
        migrations.AddField(
            model_name='proyectosaagrupar',
            name='disponibilidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Porcentaje de disponibilidad'),
        ),
        migrations.AddField(
            model_name='proyectosaagrupar',
            name='utilizacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Porcentaje de utilización'),
        ),
        migrations.AlterField(
            model_name='hh_estimado_detalle_semanal',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 23, 17, 10, 55, 164085), verbose_name='Fecha'),
        ),
    ]
