# Generated by Django 4.1.8 on 2024-08-23 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_proyectosaagrupar_desfasedias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialcambios',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='historialcambios',
            name='tipoInfo',
        ),
        migrations.AddField(
            model_name='historialcambios',
            name='categoria',
            field=models.CharField(default='No Registrado', max_length=250, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='historialcambios',
            name='subcategoría',
            field=models.CharField(default='No Registrado', max_length=250, verbose_name='Sub Categoría'),
        ),
        migrations.AlterField(
            model_name='hh_estimado_detalle_semanal',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 23, 17, 15, 18, 677510), verbose_name='Fecha'),
        ),
    ]
