# Generated by Django 4.1.8 on 2024-08-23 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_historialcambios_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcambios',
            name='prioridad',
            field=models.IntegerField(default=0, verbose_name='Priodidad'),
        ),
        migrations.AlterField(
            model_name='hh_estimado_detalle_semanal',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 23, 17, 20, 3, 680937), verbose_name='Fecha'),
        ),
    ]
