# Generated by Django 4.1.8 on 2024-08-26 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_rename_subcategoría_historialcambios_subcategoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_parametro', models.CharField(max_length=255)),
                ('valor', models.JSONField()),
            ],
            options={
                'db_table': 'PARAMETROS',
            },
        ),
        migrations.AlterField(
            model_name='hh_estimado_detalle_semanal',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 26, 16, 55, 56, 592593), verbose_name='Fecha'),
        ),
    ]
