# Generated by Django 4.1.8 on 2024-08-27 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_parametro_alter_hh_estimado_detalle_semanal_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hh_estimado_detalle_semanal',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 26, 21, 40, 4, 715592), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='nombre_parametro',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
