# Generated by Django 4.1.8 on 2024-09-09 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_hh_estimado_detalle_semanal_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hh_estimado_detalle_semanal',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 19, 35, 19, 771585), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='proyectosaagrupar',
            name='cierre',
            field=models.DateField(blank=True, null=True, verbose_name='Cierre del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyectosaagrupar',
            name='egresosNoHHCLP',
            field=models.IntegerField(default=0, verbose_name='Egresos no HH CLP'),
        ),
    ]
