# Generated by Django 4.1.8 on 2024-09-16 22:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_hh_estimado_detalle_semanal_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ultimo_ejecucion', models.DateField(blank=True, null=True)),
                ('ejecuciones_exitosas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=100)),
                ('prioridad', models.IntegerField()),
                ('horas_promedio', models.IntegerField(default=40)),
            ],
            options={
                'db_table': 'Recurso',
            },
        ),
        migrations.CreateModel(
            name='TipoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('prioridad', models.IntegerField()),
            ],
            options={
                'db_table': 'TipoProyecto',
            },
        ),
        migrations.RemoveField(
            model_name='disponibilidad',
            name='hh',
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='horas_disponibles',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='semana',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hh_estimado_detalle_semanal',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 19, 4, 29, 662702), verbose_name='Fecha'),
        ),
        migrations.AlterModelTable(
            name='disponibilidad',
            table='Disponibilidad',
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('horas_demandadas', models.IntegerField()),
                ('rol_requerido', models.CharField(max_length=100)),
                ('semana_inicio', models.IntegerField()),
                ('duracion_semanas', models.IntegerField()),
                ('tipo_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoproyecto')),
            ],
            options={
                'db_table': 'Proyecto',
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.IntegerField()),
                ('horas_asignadas', models.IntegerField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proyecto')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recurso')),
            ],
            options={
                'db_table': 'Asignacion',
            },
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='recurso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.recurso'),
            preserve_default=False,
        ),
    ]
