# Generated by Django 4.1.8 on 2024-09-16 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_asignacioncontrol_recurso_tipoproyecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hh_estimado_detalle_semanal',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 19, 5, 2, 117202), verbose_name='Fecha'),
        ),
    ]
