# Generated by Django 4.1.8 on 2024-09-25 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_horaspredecidas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaspredecidas',
            name='tipo_semana',
            field=models.CharField(default='Intermedio', max_length=20, verbose_name='Tipo de Semana'),
        ),
        migrations.AlterField(
            model_name='hh_estimado_detalle_semanal',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 16, 22, 34, 689290), verbose_name='Fecha'),
        ),
    ]
