# Generated by Django 4.1.8 on 2024-09-25 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_horaspredecidas_tipo_semana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hh_estimado_detalle_semanal',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 18, 8, 25, 340688), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='horaspredecidas',
            name='tipo_semana',
            field=models.CharField(blank=True, default='Intermedio', max_length=20, null=True, verbose_name='Tipo de Semana'),
        ),
    ]
