# Generated by Django 4.1.8 on 2024-10-04 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_asignacion_año_proyectosaagrupar_fechafin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectosaagrupar',
            name='disponibilidad',
        ),
        migrations.RemoveField(
            model_name='proyectosaagrupar',
            name='utilizacion',
        ),
        migrations.AlterField(
            model_name='hh_estimado_detalle_semanal',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 15, 39, 27, 110964), verbose_name='Fecha'),
        ),
    ]
