# Generated by Django 4.1.8 on 2024-10-11 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_hh_estimado_detalle_semanal_fecha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacion',
            old_name='año',
            new_name='anio',
        ),
        migrations.AlterField(
            model_name='hh_estimado_detalle_semanal',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 10, 21, 34, 44, 123176), verbose_name='Fecha'),
        ),
    ]
