# Generated by Django 4.1.8 on 2024-10-11 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_rename_año_asignacion_anio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='horas_asignadas',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='horas_totales',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id_empleado',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id_recurso',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='hh_estimado_detalle_semanal',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 11, 14, 32, 39, 737479), verbose_name='Fecha'),
        ),
    ]
