# Generated by Django 4.1.8 on 2024-10-11 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_alter_asignacion_horas_asignadas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hh_estimado_detalle_semanal',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 11, 16, 1, 14, 384768), verbose_name='Fecha'),
        ),
    ]
