# Generated by Django 4.1.8 on 2024-10-11 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_alter_hh_estimado_detalle_semanal_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacioncontrol',
            name='ejecuciones_fallidas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hh_estimado_detalle_semanal',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 11, 17, 23, 23, 638634), verbose_name='Fecha'),
        ),
    ]
