# Generated by Django 4.1.8 on 2024-10-11 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_asignacioncontrol_ejecuciones_fallidas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='horas_asignadas',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Horas Asignadas'),
        ),
        migrations.AlterField(
            model_name='hh_estimado_detalle_semanal',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 11, 18, 14, 37, 679250), verbose_name='Fecha'),
        ),
    ]
