# Generated by Django 4.1.8 on 2024-10-16 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_asignacion_horas_asignadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='enviado',
            field=models.BooleanField(default=False, verbose_name='Ha sido eviado a Odoo.'),
        ),
        migrations.AlterField(
            model_name='hh_estimado_detalle_semanal',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 16, 16, 15, 10, 825420), verbose_name='Fecha'),
        ),
    ]
