# Generated by Django 4.1.8 on 2024-10-17 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_asignacion_enviado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hh_estimado_detalle_semanal',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 17, 18, 6, 8, 426624), verbose_name='Fecha'),
        ),
    ]
