# Generated by Django 4.1.8 on 2024-10-21 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_empleado_activo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hh_Estimado_Detalle_Semanal',
        ),
        migrations.DeleteModel(
            name='Perfil_hh_Detalle_Semanal',
        ),
        migrations.DeleteModel(
            name='Ventas',
        ),
    ]
